apiVersion: apps/v1
kind: Deployment
metadata:
  name:  orders
  # namespace: dev
  labels:
    app:  orders
spec:
  selector:
    matchLabels:
      app: orders
  replicas: 1
  template:
    metadata:
      labels:
        app:  orders
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  orders
        image:  jobmounchili/k-orders:latest
        command: ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0"]
        resources: {}
        ports:
        - containerPort:  80
          name:  orders
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  # namespace: dev
spec:
  selector:
    app: orders
  type: ClusterIP
  ports:
  - name: orders
    protocol: TCP
    port: 8000
    targetPort: 8000
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    # nodePort: 